apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-cd
spec:
  project: hsop
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: deepika-sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sites
