apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-cli-resource
  namespace: deepika
spec:
  selector:
    matchLabels:
      app: cf-cli-resource
  replicas: 1
  template:
    metadata:
      labels:
        app: cf-cli-resource
    spec:
      containers:
      - name: cf-cli-resource
        image: nulldriver/cf-cli-resource
        ports:
        - containerPort: 8080
