name: bd scan
on: 
  push:
jobs:
  detect-scan:
    runs-on: [self-hosted, Windows, x64, jenkins-ws-551]
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@v2.2
        with:
            version: 7
            blackduck.url: ${{ secrets.BLACKDUCK_URL }}
            blackduck.api.token: ${{ secrets.BLACKDUCK_API_TOKEN }}
            args: --detect.risk.report.pdf=true