name: bd scan
on: 
  push:
jobs:
  detect-scan:
    runs-on: [self-hosted, Windows, x64, jenkins-ws-551]
    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: run detect ps script
        shell: cmd
        run: set _JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true

      - name: print var
        shell: powershell
        run: echo ${{ github.workspace }}

# file-path: ${{ github.workspace }}/build/${{ env.FILE_NAME }}.zip
# run: echo ${env:PATH}