name: bd scan
on: 
  push:
jobs:
  detect-scan:
    runs-on: [self-hosted, Windows, x64, jenkins-ws-551]
    steps:
      - name: call internal action workflow
        uses: philips-internal/blackduck-scan-sbom-action@main
        with:
          Blackduck-Project-name: deepika-argocd-proj
          Blackduck-Project-version: deepika-argocd-v1
          Blackduck-APItoken: ${{ secrets.BLACKDUCK_API_TOKEN }}